//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoga.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsan
    {
        public int AsanId { get; set; }
        public string AsanName { get; set; }
        public string Description { get; set; }
        public string Steps { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Benefits { get; set; }
        public string Precaution { get; set; }
        public string CreatedBy { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
    }
}
