//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoga.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Fatherhusbandname { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Education { get; set; }
        public string Schoolnameifstudying { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Occupation { get; set; }
        public string Mobilenumber { get; set; }
        public string Healthissueifanypleasespecify { get; set; }
        public string Address { get; set; }
        public string doyouknowaboutyogaifyespleasespecify { get; set; }
    }
}
